### ISSUE TITLE
Command: Organize imports

### ISSUE THREAD

**Issue by tomahl** [apexskier/nova-typescript#104]
Hi there,

Would you consider adding the command "[organize imports](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports)", and (if possible) a settings that would run the command on save just like in vscode.

`"[typescript]": {
		"editor.codeActionsOnSave": {
			"source.organizeImports": true
		},
	},
`

Thanks for your great work. 👍

**Comment by apexskier** [comment]
I'm pretty sure I'm not able to directly implement this for the same reasons as https://github.com/apexskier/nova-typescript/issues/52

I'll revisit this after Nova v1.3, since there will be some major changes related to actions like this.

**Comment by apexskier** [comment]
Quick update: Looks like this isn't working in v2. I'll have to investigate if it's missing from the language server implementation, or something else.

**Comment by apexskier** [comment]
I've found the root cause of this, and found two possible approaches to fix it.

1. Like VSCode, I could potentially expose a separate command to organize imports.
2. The underlying language server currently sort of excludes organize imports as a normal code action. That could be changed to return it with other code actions.

I prefer 2, so I've opened https://github.com/theia-ide/typescript-language-server/pull/170.

**Comment by tomahl** [comment]
I really appreciate your dedicated work with this extension. 👍 What I really like with VSCode is that you're able to run the command on both file save or manually within a file. But from I understand that would be doable with option 2 as well right?. :)

**Comment by apexskier** [comment]
Understandably, I'm getting a bit of push back on making this a normal code action, specifically because it will show up for every line of the document. I'm working on adding a new command for this in https://github.com/apexskier/nova-typescript/pull/129

**Comment by apexskier** [comment]
I'm going to be launching this in #129.

There's one known visual issue - if you have the preference to auto-apply on save enabled you'll see the editor "flash" as it moves content around. The editor moves your cursor to the top of the file when organizing imports, and I _try_ to move it back to the original location but can't do it perfectly.
