### ISSUE TITLE
Option to turn off TypeScript validation

### ISSUE THREAD

**Issue by jonowells** [apexskier/nova-typescript#116]
This extension is great for getting type insights in JS files and jumping to code definitions, but in some projects I need to run ESLint instead of TypeScript's validator. An option to disable inline errors/warnings from TypeScript would be useful.

**Comment by apexskier** [comment]
How would you expect this to be different than the "Enable on Javascript files" preference?

What specific errors are you seeing in JavaScript files? In my experience, the language server provides type signatures and navigation but I don't think I've actually seen errors for vanilla javascript code.

**Comment by jonowells** [comment]
Good question. And there might be some configuration I could do in jsconfig.json but yeah the extension lints your code that'd be okay but some of the warnings are things I can't fix, like this one:

<img width="662" alt="Screen Shot 2020-10-31 at 3 57 21 PM" src="https://user-images.githubusercontent.com/500474/97788900-bde4dd80-1b92-11eb-8270-d97b81f1b39d.png">

**Comment by apexskier** [comment]
You can disable this warning in your tsconfig/jsconfig file with the [`noUnusedParameters`](https://www.typescriptlang.org/tsconfig#noUnusedParameters) config option, or by prefixing your variable name with an underscore. Given that option or disabling javascript file processing, I'm going to close this issue.

**Comment by kzka90** [comment]
I'm also interested in disabling warnings of that type and other types. I'm interested in the Extension because it helps me autocomplete and see definition off vars/funcs, but I want to turn off the warnings. I do want to see them logged on the TS/JS sidebar, but I don't want to distract me while I'm developing.

**Comment by rolandleth** [comment]
@apexskier `noUnusedParameters` doesn't make the warning go away (neither prefixing it with `_`:

<img width="715" alt="Bildschirmfoto 2021-03-22 um 4 45 49 PM" src="https://user-images.githubusercontent.com/1858700/112008350-10b53680-8b2e-11eb-8f5b-dea61518a05c.png">

Even if it worked, the main issue (for me, at least) is that there's also an ESLint rule for it, but I wouldn't really want to disable it in `tsconfig` either.

**Comment by apexskier** [comment]
In version 2.4.0, you can now disable suggestions from the typescript server using this preference:

<img width="601" alt="Disable suggestions" src="https://user-images.githubusercontent.com/329222/124502919-b0888e80-ddc4-11eb-84d4-f5e14cecb21f.png">

**Comment by apexskier** [comment]
This appears to hide the unused local warning, at least
