### ISSUE TITLE
Yarn 2 PnP support

### ISSUE THREAD

**Issue by abarisain** [apexskier/nova-typescript#130]
Hello!

I'm using yarn2's zero install (PnP) mode in a project. VSCode and WebStorm can handle this (with caveats) with pnpify.
A consequence of this, is having no node_modules (they're replaced by zipped files you can commit, which has a lot of advantages), which makes it harder to boot typescript, or even index modules.

Unfortunately, pointing the extension to a pnpified typescript/lib folder (what VSCode and the TS vim plugin use as a typescript wrapper) makes it fail to load. I do still get some completion but it's not aware of my project at all.

Please tell me how I can help you if you're interested in supporting this. I'm not even sure where to get logs.

It's no big deal, as I'm thinking of going back to a more classic node_modules anyway.

**Comment by apexskier** [comment]
I'm interested in supporting PnP, but haven't played with it yet myself.

This looks like the most promising way to support it: https://yarnpkg.com/features/pnp#packages-are-stored-inside-zip-archives-how-can-i-access-their-files

I just tested quickly, and [with a `pnp` project](https://classic.yarnpkg.com/en/docs/pnp/getting-started), you can get access to the typescript server with the following:

```js
require("./.pnp.js").setup()
console.log(require.resolve("typescript/bin/tsserver"))
```

[`getTsLibPath`](https://github.com/apexskier/nova-typescript/blob/91763848df309ebe71c98b96dbcf26ef0bd04cf7/src/tsLibPath.ts#L17) needs to run that if a pnp workspace is enabled. It might/probably needs to run in an external process—I'm guessing the `.pnp.js` script won't work in the extension JSC runtime.

---

> Unfortunately, pointing the extension to a pnpified typescript/lib folder (what VSCode and the TS vim plugin use as a typescript wrapper) makes it fail to load. I do still get some completion but it's not aware of my project at all.

This surprises me a bit, and might indicate a separate bug in the project. The extension should run the server [within your workspace](https://github.com/apexskier/nova-typescript/blob/91763848df309ebe71c98b96dbcf26ef0bd04cf7/typescript.novaextension/run.sh#L5), so it shouldn't matter where the tsserver binary is. I'll test this later.

**Comment by abarisain** [comment]
Thanks! I don't mind overriding the path to tsserver manually as it's how you need to do it for vscode (use pnpify and commit .vscode)

Maybe it's the language server itself that doesn't like pnpify? I'll try to boot it manually in a terminal, I should get more logs that way.

**Comment by apexskier** [comment]
The issue with typescript I think is actually related to typescript's `@types` module resolution. I have issues when trying to build this project when it's set to use `pnp` with yarn 1. The method I mention above to get the tslib path also doesn't work with yarn 2, only with yarn 1, since yarn 2 produces paths within zip files.

This looks like it's going to also probably require using something from https://yarnpkg.com/getting-started/editor-sdks. I wasn't successful - I see `Error: Cannot find module '.../.yarn/cache/typescript-patch-e9b928397c-d4be0bd2a2.zip/node_modules/typescript/lib/typingsInstaller.js'` when I run the tsserver from the installed sdk—I don't know why that lib isn't part of the sdk patch. There's also a big caveat at the bottom that says editors need to directly support opening files in from the pnp zip file location, which I definitely won't be able to do in the extension.

**Comment by abarisain** [comment]
>This looks like it's going to also probably require using something from

I believe so too. Which is why I tried to point your extension at what yarn provides for VSCode

> There's also a big caveat at the bottom that says editors need to directly support opening files in from the pnp zip file location, which I definitely won't be able to do in the extension.

Yeah, VSCode suffers from this: I cannot "go to definition" in VSCode for anything that's part of typescript's builtin library.

Anyway I don't think it's a must have: yarn pnp doesn't have much traction, and the ecosystem doesn't seem interested in investing yarn specific support until node/npm fixes this upstream. Which I understand (and why I'm probably gonna go back to standard node_modules)

**Comment by abarisain** [comment]
I'm really not sure why this isn't working. I tried to Pnpify typescript-language-server and modified run.sh to use the local one.

Running run.sh in my terminal works, but in Nova it throws the module error, and I can't figure out why.

**Comment by abarisain** [comment]
I've come to the conclusion that typescript-language-server is broken with yarn pnp, so this is outside the scope of this project.

You can patch this extension to try it out by replacing "node" in run.sh with

```
yarn run typescript-language-server \
	--stdio \
	--tsserver-path="$TSLIB_PATH/tsserver.js"
```

and setting tslibPath to `.yarn/sdks/typescript/lib`

You will then need to install typescript-language-server in your project.

It's obviously quick & dirty, but I'm not really interested in pursuing this any further. Yarn pnp also breaks eslint and is generally buggy, so I'm giving up on this altogether

**Comment by merceyz** [comment]
> Yarn pnp also breaks eslint and is generally buggy, so I'm giving up on this altogether.

eslint or PnP? If you found any bugs, please do report them

**Comment by abarisain** [comment]
Oh sorry, I meant that Yarn PnP also breaks the nova eslint extension

**Comment by apexskier** [comment]
Thanks for your investigation! I'm going to close this for now, but hopefully we can revisit in future.

**Comment by abarisain** [comment]
Thanks for your time, sorry for not realizing it was not an extension problem before opening this!

**Comment by dlindenkreuz** [comment]
Unfortunately, the lack of PnP support is keeping us from using Nova. Yarn 2 and 3 default to PnP for installing packages. We have been using this feature since the inception of our company to reduce deploy times and improve DX.

**Comment by stackptr** [comment]
It seems likely that there has been more support for PnP in the ecosystem over the past three years. I see that there is an [editor SDK for eslint][0] listed in the Yarn documentation that might address some of the problems above. Could this issue be revisited? Are there other obvious blockers to support?

[0]: https://yarnpkg.com/getting-started/editor-sdks#tools-currently-supported
