### ISSUE TITLE
Pre-populate Rename Symbol palette with current value

### ISSUE THREAD

**Issue by alex-ketch** [apexskier/nova-typescript#133]
For me, most of the time when renaming a symbol it's to fix a minor typo or adjust the existing name.
The current behaviour is to show placeholder text that can't be selected or edited, requiring the user to type out the full name of the symbol.

**Current prompt**
<img width="516" alt="Screenshot 2020-11-19 at 11 37 28@2x" src="https://user-images.githubusercontent.com/1646307/99695901-1bff3500-2a5c-11eb-80c1-8309ea7a98a7.png">

I propose populating both the `placeholder` and [`value` options](https://docs.nova.app/api-reference/workspace/#showinputpanel-message-options-callback) to make edits easier. This UX would also bring the workflow in line with how VS Code works.

The change would be made at the following place:

https://github.com/apexskier/nova-typescript/blob/63a35d0746b62446b20088170195b9305d8ee75e/src/commands/rename.ts#L32

~I can make the PR if this change sounds good.~

Never mind, the `InputPalette` API doesn't support the `value` option, only the `InputPanel` one does. Will report as a feature request on the Nova dev forum.

**EDIT:** The feature request forum post can be [found here](https://devforum.nova.app/t/allow-passing-value-option-to-showinputpalette-api/477).

**Comment by apexskier** [comment]
This is definitely what I want to do, but as you've seen it's not supported without moving to the input panel, which I don't like as much. Can you link to the thread in the dev forum when you've posted?
