### ISSUE TITLE
An error is reported for decorators in JS & JSX files, even though `"experimentalDecorators": true` is set in config

### ISSUE THREAD

**Issue by Orangetronic** [apexskier/nova-typescript#140]
If I enable type checking for js files, decorators show a type error even though I have `experimentalDecorators` set true in tsconfig. 

I have created a little example repo here which exhibits this issue: https://github.com/Orangetronic/nova-typescript-decorator-issue-reproduction

**Expected behavior**

I'd expect `"experimentalDecorators": true` to apply to JS/JSX files as well as TS/TSX

**Screenshots**

<img width="672" alt="Screenshot 2020-11-30 at 16 23 39" src="https://user-images.githubusercontent.com/1311841/100635432-6b7d1500-3328-11eb-9245-1fd72dab538a.png">

**Environment**

- Nova version: 221256
- Extension version: 2.1.0
- TypeScript version: 4.0.5 (also seen with 4.1.2, and 3.something)
- Sidebar information: Status Running, TypeScript Version 4.0.5
- macOS version: 11.0.1 (20B29)
- NodeJS information:
  - node version: 14.7.0
  - npm version: 6.14.8
  - installation method: `n`

**Extension console output**
```
TypeScript[16:05:20.424000] reloading...

TypeScript[16:05:20.434000] dependencyManagement: claimed lock

TypeScript[16:05:21.728000] dependencyManagement: installing: audited 19 packages in 0.646s

TypeScript[16:05:21.880000] dependencyManagement: installing: found 0 vulnerabilities

TypeScript[16:05:21.881000] dependencyManagement: installing: 

TypeScript[16:05:21.888000] dependencyManagement: clearing lock

TypeScript[16:05:21.892000] using tslib at: /Users/[redacted]/Library/Application Support/Nova/Extensions/apexskier.typescript/dependencyManagement/node_modules/typescript/lib
```

**Comment by Orangetronic** [comment]
If anybody can point me in the right direction, I'd be up for taking a crack at this 😸

**Comment by apexskier** [comment]
Thanks for the reproduction repository!

It looks like the issue is resolved if you enable TypeScript processing on javascript files - turning on `allowJs` fixes this for me. I'd recommend enable that for your project or [disabling the extension from processing on javascript files](https://github.com/apexskier/nova-typescript/blob/master/typescript.novaextension/README.md#enabledisable-for-javascript).

https://github.com/Orangetronic/nova-typescript-decorator-issue-reproduction/compare/main...apexskier:main

**Comment by apexskier** [comment]
Unfortunately, I don't think there's anything else I can do about this directly, although there might be a possible fix in the language server implementation.

**Comment by Orangetronic** [comment]
hey that's really helpful — I'll give that a go, thank you 🙌 

I reckon if there's a config way around it, then there's probably no further action needed on your end. Shall I close this?

**Comment by apexskier** [comment]
That'd be great, thanks!

**Comment by Orangetronic** [comment]
This can be solved in config via the `allowJs` flag
