### ISSUE TITLE
TSX / JSX differences in syntax highlighting

### ISSUE THREAD

**Issue by benvp** [apexskier/nova-typescript#141]
Hey! First of all, thanks for the great extension. While making my own theme, I noticed that there are a few differences between the highlighting of tsx and jsx files. I'd like to colour my react component template code (the jsx part) to be different on tags/properties/values.

Using the syntax inspector, it seems that there are no css classes to refer to when using a TSX file whereas there are specific classes when using a JSX file type. I'm referring to the `scopes` section in the screenshots.

Is this a concern of this extension or native to nova? I would be happy to help and provide a PR if someone could point me into the correct direction. 🙃

**Edit:** Seems that this is related to nova's internal syntax highlighting (https://github.com/apexskier/nova-typescript/issues/68). Will send a request to the nova team.

TSX:
![image](https://user-images.githubusercontent.com/981344/100972787-a7d38f80-3539-11eb-848c-c9688f1cab3a.png)

JSX:
![image](https://user-images.githubusercontent.com/981344/100972826-b91c9c00-3539-11eb-9268-4e287e0db44f.png)

**Comment by apexskier** [comment]
As you've seen in #68, this isn't part of this extension. I'm going to close this as a duplicate, but keep an eye on #68 for any updates.
