### ISSUE TITLE
Pressing `.` automatically chooses the selected completion suggestion

### ISSUE THREAD

**Issue by gwhobbs** [apexskier/nova-typescript#160]
Pressing `.` automatically chooses the selected completion suggestion. This frequently results in undesirable behavior—for example, `console.log` is often transformed into `Console.log`. When not using this extension, Nova keeps whatever was typed unless e.g. `tab` was pressed. 

**To reproduce**

1. Start typing something that produces a completion suggestion
2. Press `.`

**Expected behavior**

The typed text is unaltered.

**Screenshots**

![log](https://user-images.githubusercontent.com/4071958/103445306-f60ea800-4c37-11eb-8a7f-29912e468d68.gif)

**Environment**

- Nova version: 3.1 (211256)
- Extension version: 2.1.0
- TypeScript version: 4.1.3 (problem seems to affect other versions as well)
- Sidebar information: `Status Running` `Typescript Version Version...`
- macOS version: 10.15.7 (19H114)
- NodeJS information:
  - node version: v14.15.1
  - npm version: 6.14.9
  - installation method: n

**Extension console output**

No Typescript-related output generated when problem occurs. 

**Additional context**

I have experienced this issue since Nova was in beta.

**Comment by apexskier** [comment]
This is actually a "feature" of the language server the extension uses and [language server protocol](https://microsoft.github.io/language-server-protocol/specifications/specification-current/).

https://github.com/theia-ide/typescript-language-server/blob/3a8ea0f04bde047e2f60b9f68ef7816e3a41aa10/server/src/lsp-server.ts#L147

I also find this a bit annoying - I'll investigate if there's a way to override the default.

**Comment by zaceno** [comment]
I will also add that pressing comma (`,`) inside object literals has the same annoying behavior. If there's a way to override the `.` forcing autocompletion I hope it would be possible to override this comma-behavior as well.

An example: I type: `let foo = {bar: 2` ...press "," ... and the result is `let a = {b: Path2D,` 😓 

It seems over-eager to chose completions that aren't even a very close match, like matching `2` to `Path2D`, or `4` to `Float64Array`. Usually when I type a number all I mean to type is a number.

**Comment by logancollins** [comment]
We've heard a couple of reports about this from other users in Nova as well. @apexskier, if there's anything we need or could do from our side to make things better for the LSP extension, please let us know!

**Comment by exPHAT** [comment]
Huge +1 on this. Super annoying when the autocomplete re-prompts even after editing my mistake (then I proceed to have the autocomplete win 2-3 more times before I can type what I want).

Any update on overriding the default?

**Comment by apexskier** [comment]
I wasn't able to find a way to override through `typescript-language-server` or the language server protocol itself, so I don't have any ideas of how Nova could address it cleanly.

It looks like the [original reason](https://github.com/theia-ide/typescript-language-server/pull/50) for this was [to match VSCode behavior which still exists](https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/languageFeatures/completions.ts#L815-L821). I played around a bit and it appears that VSCode does the same thing as nova with respect to replacing with the chosen suggestion. The _actual_ issue might be that the ordering of suggestions is a lot worse in Nova/this extension.

| VSCode | Nova |
| --- | --- |
| ![VSCode autocompletion](https://user-images.githubusercontent.com/329222/108530929-65b72000-72d6-11eb-881b-1e66425dbdef.mp4) | ![Nova autocompletion](https://user-images.githubusercontent.com/329222/108531178-b3cc2380-72d6-11eb-8f04-df62de51e77d.mp4) |

**Comment by apexskier** [comment]
After a quick scan, I don't see any sorting logic in vscode or the language server.

**Comment by apexskier** [comment]
> The _actual_ issue might be that the ordering of suggestions is a lot worse in Nova/this extension.

I'm doing some more digging, and it also seems like the filtering logic is different from VSCode.

**Comment by apexskier** [comment]
@logancollins Does Nova do a full `completionItem/resolve` when applying autocompletion? I'm not seeing the [server method called](https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-server.ts#L462-L468) when I choose an item. This is important for items with associated commands/text edits for tsserver, it looks like, so it might be causing "broken" autocompletions.

**Comment by zaceno** [comment]
@apexskier just want to say thanks for digging in to this and keep up the good work! Happy hunting!

**Comment by logancollins** [comment]
@apexskier Correct, Nova does not currently support the resolve request in the Language Server Protocol. We hope to look into adding support for this at some point. I can see if we can try and schedule this for the next feature milestone. So far, we haven't encountered (or heard encounter of) any LSPs actually using it, but clearly it would be required for full tsserver support.

I would imagine the item ordering algorithm used by Nova is not exactly the same as VSCode. Nova uses an n-gram sorting algorithm that allows for fuzzy-matching. I am aware that the LSP completion items can optionally provide a string override for use when sorting, but Nova currently ignores it. It may be worth it for us to revisit this and see if there's a better way we can ensure that items returned from a language server can maintain their ordering relative to each other, while still applying fuzzy matching and allowing the rest of Nova's completion providers to inter-sort properly.

I am not offhand sure what they might be doing, as I generally tend to avoid reading the VSCode source to avoid any reverse engineering legal issues from our perspective. (Call me paranoid, I guess. 😄)

**Comment by apexskier** [comment]
From what I saw in VSCode source, they're using the `sortText` concept from the language server protocol (not directly, but the same concept). Support for that would significantly help here I think.

**Comment by abelespana** [comment]
The latest Nova update (7.0, released yesterday) fixes the problem for me. Great job!

**Comment by apexskier** [comment]
@abelespana interesting. I still see `.` and `,` act as a trigger characters. The suggestions might have improved (`Console` is no longer suggested) but I think that was a prior release.

**Comment by Corack117** [comment]
I have the same problem, when I use. " or "," I do the self-tasting, I had to deactivate the section of Completions so that the problem does not happen, unfortunately, remove several increasing when programming

Nova version: 7.4
Typescript extension:  2.4.0

**Comment by michaelflores-italic** [comment]
I will say I've also found this to be quite problematic, and just generally felt the auto-complete in Nova was wonky to the point of generating multiple bug reports but it's hard to tell at times whether it's Nova or this extension the root cause is in. Curious at this point if there is anything planned or further work that could be done on improving this particular issue (happy to try and help), or is it still on Nova to fix it? I still have this behavior in Nova 8.1 and when I emailed them about it, they referred to the extension.

**Comment by logancollins** [comment]
You will all likely be very happy to hear that we've added an explicit preference to the upcoming Nova 9 to disable completion trigger characters defined by language servers. This should prevent characters like `.` from accepting the selected completion item. I regret that it's taken us so long to finally do this.

**Comment by codebykenny** [comment]
@logancollins this is great news, is there a way to get access to the Nova 9 version as a tester? Unfortunately in my projects, this particular issue makes Nova 8 unusable. The "." key randomly inserts characters as I type

https://user-images.githubusercontent.com/6720728/154741764-c037a50f-239b-4567-97db-3cd7d04fbeb0.mp4

**Comment by apexskier** [comment]
Nova 9 has been released
