### ISSUE TITLE
Organize multi-line imports indents wrong

### ISSUE THREAD

**Issue by davidenke** [apexskier/nova-typescript#236]
Using the option "Organize imports on save" uses wrong indentions if imports are wrapped.

**To reproduce**

1. Set the indention in the settings to 2 spaces
2. Add multiline import to a typescript file
3. The indention is changed two 4 spaces

**Expected behavior**

The organized imports shall stay indented by two spaces

**Screenshots**
![2021-04-19 14 08 00](https://user-images.githubusercontent.com/275960/115234969-eb5e1d00-a119-11eb-90b9-e6aea0c9c386.gif)

**Environment**

- Nova version: 5.1 (257074)
- Extension version: 2.1.1
- TypeScript version: 4.1.3
- Sidebar information:  Status Running, TypeScript Version 4.1.3
- macOS version: 11.2.3 (20D91)
- NodeJS information:
  - node version: v14.16.0
  - npm version: 6.14.11
  - installation method: nvm

**Extension console output**
None.

**Comment by apexskier** [comment]
<details>

<summary>Some notes:</summary>

VSCode's "Organize Imports" command doesn't do this, but I can reproduce it in Nova.

The organize imports functionality is provided by the language server through tsserver. It looks like there's some sort of formatting context provided, so I want to see if it's correct at runtime.

https://github.com/theia-ide/typescript-language-server/blob/b9cf57816ca07b9b3f3631130b7b5250b0db7ced/server/src/lsp-server.ts#L742-L750

https://github.com/microsoft/TypeScript/blob/3d24b85f9e5dde6f35d6014539aeef9801e74493/src/services/organizeImports.ts#L12-L15

The typescript language server has the opportunity to configure the formatting options for tsserver - https://github.com/theia-ide/typescript-language-server/blob/b9cf57816ca07b9b3f3631130b7b5250b0db7ced/server/src/lsp-server.ts#L125-L129

VSCode configures tsserver here - https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/extensions/typescript-language-features/src/languageFeatures/fileConfigurationManager.ts#L70-L92

</details>

Thanks for the report! I've found a way to fix this and should be able to get it into the next release.
