### ISSUE TITLE
Extension error in console.

### ISSUE THREAD

**Issue by mikebronner** [apexskier/nova-typescript#254]
**Steps to reproduce the behavior:**
Unfortunately I don't know what caused this.

**Environment**
- Nova version: 6.2
- Extension version: 2.3.0
- TypeScript version: n/a
- Sidebar information: Status Running, TypeScript Version 4.2.4
- macOS version: 11.4.beta2
- NodeJS information:
  - node version: 14.4.5
  - npm version: 6.14.5
  - installation method: installed from distribution installer downloaded from nodejs website

**Extension console output**
```
TypeScript Language Server[15:05:20.051000] [tsserver] npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @types/browserslist@4.15.0: This is a stub types definition. browserslist provides its own type definitions, so you do not need this installed.
```

**Comment by apexskier** [comment]
I think this is project specific - this extension doesn't have `@types/browserlist` in the dependency tree and has newer versions (newer than those recommendations) of `fsevents` and `chokidar`.

But, I'm not reproducing on TypeScript 4.2.4, node 14, npm 6 in a test project with `fsevents@1.2.13` and `typescript@4.2.4` installed.

* Is this actually causing bad behavior, or just showing up as a warning in the console?
* What's the package.json/lockfile for your current project? (What has those specific packages/versions installed?)
* If you run a npm/yarn install in the project, do you see these same warnings?

If this is actually project specific and isn't causing functional issues I'm probably going to close.
