### ISSUE TITLE
Lines beginning with semicolon get indented

### ISSUE THREAD

**Issue by michaelmcauley** [apexskier/nova-typescript#271]
**To reproduce**

1. Configure TypeScript extension to format document on save
2. Edit a .ts file and insert a line beginning with a semicolon (see screenshots below for example)
3. Save the file
4. Observe that lines beginning with semicolon are indented despite being in the same block as the preceding line

**Expected behavior**

Lines beginning with a semicolon should not be indented but remain at the same indent level as the rest of their block

**Screenshots**

<img width="1257" alt="Screen Shot 2021-06-18 at 11 04 21 AM" src="https://user-images.githubusercontent.com/1678384/122581413-05867f80-d025-11eb-99e9-9d694f5bceac.png">
<img width="1257" alt="Screen Shot 2021-06-18 at 11 04 45 AM" src="https://user-images.githubusercontent.com/1678384/122581418-06b7ac80-d025-11eb-98e7-6ee068ea14fd.png">

**Environment**

- Nova version: 6.2 (271290 ) 
- Extension version: 2.3.0 
- TypeScript version: 3.9.7 
- Sidebar information: Status Running, TypeScript Version 3.9.7 
- macOS version: 11.3 (20E232 ) 
- NodeJS information:
  - node version: v15.14.0 
  - npm version: 7.7.6 
  - installation method: nvm 

**Extension console output**

Prettier[11:08:51.669000] Formatting /Volumes/Macintosh HD/Users/mike/code/janus-api/src/api/bots/botRun.resolver.ts
Prettier[11:08:51.753000] No changes for /Volumes/Macintosh HD/Users/mike/code/janus-api/src/api/bots/botRun.resolver.ts

**Additional context**

I do have Prettier extension installed (alexanderweiss/nova-prettier) and the only thing logged to console is coming from that. But if I disable TypeScript extension then these unwanted indentations no longer happen when using this Prettier extension.

**Comment by apexskier** [comment]
This is behavior of the TypeScript language's formatting functionality provided by tsserver, which this extension wraps but doesn't control. Although I don't see this explicitly reported, there are a lot of [similar looking indentation bugs reported in the typescript GitHub repo](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+indent+label%3ABug+label%3A%22Domain%3A+Formatter%22+).

To double check, I tested with these settings in VSCode and saw the same behavior.

```
 {
   "typescript.format.enable": true,
    "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    }
}
```

**Comment by apexskier** [comment]
Realistically, I don't see this being fixed. I'd be surprised if the TypeScript team is focused much on fixing formatting issues, given the popularity of prettier. I exposed the functionality since [it's easy](https://github.com/apexskier/nova-typescript/blob/2d4c1d8e61ca4afba6ee9ad1977a765e8cd0f037/src/commands/formatDocument.ts#L5-L43) and available, but don't use it personally.
