### ISSUE TITLE
Pull out generic LSP code into a new package?

### ISSUE THREAD

**Issue by sgwilym** [apexskier/nova-typescript#284]
Hey! I've recently released https://github.com/sgwilym/nova-deno, which contains a fair bit of code that I've more or less copied or pasted from this repo. So thank you, it's really been invaluable!

Given the universal utility of a lot of these utilities, how would you feel about working together to pull them out into a new module and make them a little more generic? I'm happy copy and pasting for now, but it's easy to imagine how it could benefit the fledgling Nova extension community.

The only wrinkle I can see from here is that I'd like to be able to import a module like this into Deno — but I know CDNs like Skypack handle that for you. The only thing it would need to avoid are any dependencies which rely on Node.

**Comment by apexskier** [comment]
I'm totally in favor of this.

I have https://github.com/apexskier/nova-extension-utils which has some some similar goals and could serve as a home if it made sense - its runtime is Nova, so it shouldn't depend on Node. (There are definitely other improvements that could be made if we ended up putting an LSP module in it). I haven't worked with Deno on anything real, so I'd need to pull down your extension and play with it a bit.
