### ISSUE TITLE
Failed to Install: env: npm: No such file or directory

### ISSUE THREAD

**Issue by mgmarlow** [apexskier/nova-typescript#286]
Attempting to install & activate this extension fails:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/3778552/127025204-530382ab-6e6f-48ac-9b27-32ab2abd7057.png">

I did some poking around in past issues and found #128 which failed for what appears to be a similar reason. Looking at my `Library/Application Support/`, I don't see a `Nova/Extensions` directory, so I wonder what [globalStoragePath](https://docs.nova.app/api-reference/extension/#globalstoragepath) is being referenced by the install script.

I'm new to Nova, so this is a relatively clean install with few configurations. My `.zprofile` is configured properly with `nvm`, and zsh is the default shell in Nova.

**To reproduce**

1. Install TypeScript extension
2. Observe TypeScript extension failing initialization

**Expected behavior**

Expect the TypeScript extension to successfully initialize.

**Environment**

- Nova version: 293145
- Extension version: 2.4.0
- TypeScript version: 4.3.5
- Sidebar information: Status: Failed to Install
- macOS version: 11.4; intel
- NodeJS information:
  - node version: v14.16.1
  - npm version: 6.14.12
  - installation method: nvm

**Extension console output**

```
TypeScript[9:27:51.355000] activating...

TypeScript[9:27:51.364000] dependencyManagement: claimed lock

TypeScript[9:27:51.383000] dependencyManagement: installing: env: npm: No such file or directory

TypeScript[9:27:51.384000] dependencyManagement: clearing lock

TypeScript[9:27:51.388000] Failed to activate

TypeScript[9:27:51.388000] Error: Failed to install:

env: npm: No such file or directory
```

**Comment by apexskier** [comment]
It's going to be something with your npm setup, most likely, and npm not being available in .

Can you do some experimenting to check the executable from some fresh shells? Open a fresh Local Terminal window in Nova and a fresh window in Terminal.app, run this script from both, and share the outputs:

```sh
echo $SHELL
ls -l $(command -v npm)
npm --version
```

<details>

<summary>My example:</summary>

**Terminal.app**

```
Last login: Thu Aug  5 19:22:48 on ttys005
cameronlittle@Nisqually:~
❯ echo $SHELL
ls -l $(command -v npm)
npm --version
/usr/local/bin/bash
lrwxr-xr-x  1 cameronlittle  admin  33 Jul  3 14:27 /usr/local/bin/npm@ -> ../Cellar/node@14/14.17.0/bin/npm
6.14.13
cameronlittle@Nisqually:~
❯ 
```
<img width="568" alt="cameronlittle — -bash — bash - Terminal - 2021-08-05 at 19 23 04" src="https://user-images.githubusercontent.com/329222/128393958-24fb7013-0813-4e8b-b664-df1dcee2eeba.png">

**Nova local terminal**
```
cameronlittle@Nisqually:~
❯ echo $SHELL
/usr/local/bin/bash
cameronlittle@Nisqually:~
❯ ls -l $(command -v npm)
lrwxr-xr-x  1 cameronlittle  admin  33 Jul  3 14:27 /usr/local/bin/npm@ -> ../Cellar/node@14/14.17.0/bin/npm
cameronlittle@Nisqually:~
❯ npm --version
6.14.13
cameronlittle@Nisqually:~
❯ 
```
<img width="977" alt="cameronlittle – bash – 137×50 - Nova - 2021-08-05 at 19 24 26" src="https://user-images.githubusercontent.com/329222/128394116-38d698e0-4334-4e76-b629-d4858a3e8fc4.png">

</details>

**Comment by mgmarlow** [comment]
No problem!

I was able to resolve this issue by installing a version of `node` via brew--previously I was relying entirely on [nvm](https://github.com/nvm-sh/nvm). I assume my issue here had to do with the extension not finding my version of `node`/`npm` when initialized with `nvm`, probably due to the funkiness of using `nvm` with my default shell of `fish`.

Here is the output of my integrated Nova terminal:

```
% echo $SHELL
/usr/local/bin/fish # (fish because my system default is fish, but Nova uses zsh)
% ls -l $(command -v npm)
lrwxr-xr-x  1 user.me  staff  38 Apr  6 08:22 /Users/user.me/.nvm/versions/node/v14.16.1/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
% npm --version
6.14.12
```

I'm going to close out this issue since I have a workaround and is probably specific to my combination of shells + nvm node installation.

Thanks for taking the time to reply!
