### ISSUE TITLE
Crashes Nova

### ISSUE THREAD

**Issue by marcosjampietri** [apexskier/nova-typescript#298]
It crashes Nova whenever you get to a point in the undo history. It also loses completely the highlight for the language occasionally on delete (P.S. I'm using Neon theme if that's relevant)

**To reproduce**

apply a few undos to a TS or TSX file.

**Environment**

- Nova version: 7.2
- Extension version: 2.4.0
- TypeScript version: 4.3.5
- Sidebar information: ?
- macOS version: 11.5.1
- NodeJS information:
  - node version: v14.17.3
  - npm version: 6.14.13
  - installation method: built from source

**Extension console output**
couldn't get that info.

**Comment by jfieber** [comment]
Nova [7.3 and 7.4](https://nova.app/releases/) addressed a number of crashing issues, at least some of which were introduced in 7.2.

**Comment by marcosjampietri** [comment]
It's been q while I don't have the issue anymore. I hope it's solved.

**Comment by apexskier** [comment]
FYI, Nova 8 brought back several crashes - see https://github.com/apexskier/nova-eslint/issues/231
