### ISSUE TITLE
Suppresses static JavaScript completions

### ISSUE THREAD

**Issue by kopischke** [apexskier/nova-typescript#299]
With the TypeScript extension active, Nova stops offering completion suggestions in JavaScript files. Note by this I mean the static completions that come with Nova out of the box, not clips (I am aware of #86, but that was strictly clips and has been closed, which suggests this is a different bug).

**To reproduce**

1. Deactivate all extensions.
2. Open a new JS document.
3. Type “A”.
4. Nova suggests “Array” (et al.) as completion.
5. Activate the TypeScript extension.
6. Type “r” after the ”A” from step 4.

**Expected behavior**

Nova suggests “Array” (et al.) as completion.

**Actual behavior**

Nova does not suggest completions.

**Environment**

- Nova version: 7.4 (310378)
- Extension version: 2.4.0
- TypeScript version: not in project
- Sidebar information: Status Running, TypeScript Version 4.3.5
- macOS version: 11.5.2
- NodeJS information:
  - node version: v16.8.0
  - npm version: 7.21.0
  - installation method: homebrew

**Extension console output**

“TypeScript” console shows “activated”. The “TypeScript Language Server” console complains about `/user/local/Cellar/node/16.8.0/bin/npm` not being found (homebrew’s `npm` is a symlink to `/usr/local/lib/node_modules/npm/bin/npm-cli.js`).

**Comment by kresdjan** [comment]
Same with `for` in both .ts and .js

nova-typescript disabled ↓
<img width="1112" alt="without-nova-ts" src="https://user-images.githubusercontent.com/17638455/139589226-f77943cb-d26a-48a9-be16-06b153b982cc.png">

nova-typescript enabled ↓
<img width="1112" alt="with-nova-ts" src="https://user-images.githubusercontent.com/17638455/139589261-764b7e59-0832-463e-9e59-496290193f71.png">

**Comment by kresdjan** [comment]
What is the status? Can this be fixed?

**Comment by JimFrostig** [comment]
It seems to work for me, when I manually restart the tsserver (kill it by the terminal and restart it with the extension). Maybe that's related and can help you fix this ?
<img width="819" alt="Bildschirmfoto 2022-04-03 um 21 44 37" src="https://user-images.githubusercontent.com/6785519/161445365-46113f2a-4cd7-4efb-b086-37cd946bfdc0.png">

**Comment by kresdjan** [comment]
That is great. I still can't get Nova's snippets working. Seems like they can't coexist with the TypeScript extension completion.

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
