### ISSUE TITLE
Error: Failed to install:  env: npm: No such file or directory

### ISSUE THREAD

**Issue by jbree** [apexskier/nova-typescript#310]
I know this bug has been reported a number of times. I'm sharing my experience in case it helps find the root cause, or perhaps just helps another person work around it.

I traced this back to the [oh-my-zsh](http://ohmyz.sh) shell configuration manager, specifically with tmux installed, enabled and auto-started.

Here's a minimal .zshrc that, when oh-my-zsh and tmux are installed, causes the nova-typescript extension to throw up the "failed to install" error:

```
export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH="/Users/<user>/.oh-my-zsh"

plugins=(tmux)

ZSH_TMUX_AUTOSTART=true

source $ZSH/oh-my-zsh.sh
```

**Comment by EmranMR** [comment]
Yea I seem to get the same message in the console` [tsserver] /bin/sh: /usr/local/Cellar/node/17.4.0/bin/npm`

the npm directory is /`usr/local/bin/npm `on my system.

They were  installed via brew. surely there is a way to change the path for the extension?

**Comment by apexskier** [comment]
I see this same message as well, with no negative side effects.
