### ISSUE TITLE
Performance issues after Nova 9

### ISSUE THREAD

**Issue by sgwilym** [apexskier/nova-typescript#368]
After updating to Nova 9 I'm starting to experience some performance issues with this extension. It's hard to pin down and give proper reproduction instructions, but here's what I've noticed:

- The extension struggles to keep up with my typing, ofter only updating contextual information after several seconds.
- One time when opening code actions for a line, I could see code actions for past states of the file, e.g. `Add missing function declaration 's'`, `Add missing function declaration 'su'`  `Add missing function declaration 'sub'` `Add missing function declaration 'subt'`, etc. all listed at once. Almost as though many LSP servers were active at once.
- This problem seems to get worse the longer a file is.

**Comment by geoffb** [comment]
I'm also experiencing these performance issues post Nova 9.

**Comment by lkellar** [comment]
I'm also experiencing these issues. Most common spot I notice is after a `; newline`, the editor'll freeze, as if it's processing something

**Comment by lkellar** [comment]
![CleanShot 2022-04-13 at 14 48 18](https://user-images.githubusercontent.com/28833934/163258627-f29703fb-bcb9-4943-9822-b29e16bc8fe7.png)
Turning off completions seems to resolve it, at least for me, but this isn't great

**Comment by TheJoffrey** [comment]
Same here. It is very annoying. @apexskier are you aware of it and are you still involved in this extension?
Thanks. 😊

**Comment by apexskier** [comment]
Yeah, I'm still aware, sorry for the lack of response on my part. I'm hoping to have more time to support this next month, but I'll try to get to any PRs if I see them before then.

Unfortunately, I don't have any immediate ideas on how to fix a performance issue like this, so it'll take some deep diving. Please make sure you're reporting to Panic as well, since it was associated with a major version change.

**Comment by ziming** [comment]
I came from laravel and got the shock of my life seeing nova 9. I thought I have time traveled.

**Comment by TheJoffrey** [comment]
> Yeah, I'm still aware, sorry for the lack of response on my part. I'm hoping to have more time to support this next month, but I'll try to get to any PRs if I see them before then.
> 
> Unfortunately, I don't have any immediate ideas on how to fix a performance issue like this, so it'll take some deep diving. Please make sure you're reporting to Panic as well, since it was associated with a major version change. 

Thanks for your answer! I will report it to Panic.

**Comment by apexskier** [comment]
I've upgraded the underlying `typescript-language-server` from v0.5.4 to v0.11.0 ([changelog](https://github.com/typescript-language-server/typescript-language-server/blob/v0.11.0/CHANGELOG.md)). There's a chance that this will have helped here, please report back.

**Comment by DominicHolmes** [comment]
Haven't noticed issues 2 and 3 in my initial usage (installed today) but I'm experiencing lots of lag and hitches when typing (including rainbow wheel) on Nova 9.3, M1 Pro.

**Comment by danjguzman** [comment]
I am experiencing this issue as well and had to disable this extension to be able to type. I do remember it being a _small_ issue a year ago on my Mac Mini with _some_ stalling.

Now I'm on a Mac Studio M1 Max, and while typing, it often stalls and it'll show the "beach ball of death" which spins for up to 10 seconds before resuming and then stalling again soon after if I continue typing on the same line — it seems random too.

The performance issues on Mac Studio compared to the Mac Mini (Intel) is worse.

**Comment by davidbdyer** [comment]
I'm also experiencing this issue.

**Comment by apexskier** [comment]
I've upgraded the underlying language server and bundled typescript version, can you check this again?

**Comment by lucasfischer** [comment]
It's still slow for me.

**Comment by Sam-Spencer** [comment]
Painfully slow as of Nova 11.4.

I noticed a lot of folks are mentioning performance issues on Apple Silicon Macs, but I'd like to chime in here that my **Intel** i9 (2.3 GHz 8-core) MacBook is experiencing the same issue. I don't think this is isolated to Apple Silicon. 

And, I'm not sure it seems to be a Nova problem as suggested earlier. Disabling this extension resolves all performance issues in the editor -- even when using other extensions that provide completions from language servers.

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
