### ISSUE TITLE
node: command not found

### ISSUE THREAD

**Issue by moskoweb** [apexskier/nova-typescript#433]
It does not recognize the Node installed on the mac by Brew, and only the extension does not recognize it. At times it works and suddenly stops working.

**To reproduce**

1. Install Extension and Active
2. Show Debug Console
3. See error

**Screenshots**
<img width="1488" alt="Captura de Tela 2022-11-25 às 08 43 06" src="https://user-images.githubusercontent.com/6052272/203978723-ca863acd-7a27-4c4a-a4fa-cf699ec7c308.png">

**Environment**

- Nova version: 10.2
- Extension version: 2.5.0
- TypeScript version: 4.9.3
- Sidebar information: Stopeed
- macOS version: 13.0.1
- NodeJS information:
  - node version: v19.1.0
  - npm version: 8.19.3
  - installation method: homebrew

**Extension console output**

TypeScript[8:35:12.877000] dependencyManagement: installing: 
TypeScript[8:35:12.877000] dependencyManagement: installing: up to date in 127ms
TypeScript[8:35:12.878000] dependencyManagement: installing: 
TypeScript[8:35:12.878000] dependencyManagement: installing: 12 packages are looking for funding
TypeScript[8:35:12.878000] dependencyManagement: installing:   run `npm fund` for details
TypeScript[8:35:12.885000] dependencyManagement: clearing lock
TypeScript[8:35:12.887000] using tslib at: /.../node_modules/typescript/lib
TypeScript[8:35:12.921000] activated
TypeScript Language Server[8:35:13.715000] /.../Library/Application Support/Nova/Extensions/apexskier.typescript/run.sh: line 12: node: command not found
TypeScript Language Server[8:35:13.724000] TypeScript Language Server connection closed unexpectedly: Task exited with a non-zero exit status: 127.

**Comment by apexskier** [comment]
This is generally due to a misconfigured login shell. If you've recently changed, ensure you do a system macos restart.

**Comment by moskoweb** [comment]
No way, I installed Node by Brew, and gave this error, the clean installation of Node.

Simply the way it is running node, does not recognize the path of the command, I was able to solve it by modifying the run.sh file, to use the absolute path of the node installation.

```sh
/opt/homebrew/bin/node \
                "$INSTALL_DIR/node_modules/typescript-language-server/lib/cli.js" \
                --stdio \
                --tsserver-path="$TSLIB_PATH/tsserver.js"
```

**Comment by moskoweb** [comment]
You could have an option to set the Node path, in cases where the plugin cannot use the command.

**Comment by apexskier** [comment]
I'm not planning to add an option to set the node path, as this explicitly indicates something wrong with your setup, if Nova can't find the node executable.

If you go to "Preferences" > "Tools", ensure your environment variables contain the same `$PATH` you see when you use a normal terminal. This `$PATH` is what Nova sends to the `run.sh` script, and is what's used to resolve the `node` executable.

<img width="575" alt="Screen Shot 2023-01-17 at 8 11 47 AM" src="https://user-images.githubusercontent.com/329222/212951956-fbb2852c-a3d0-4268-ac30-91405cdc5e5a.png">

**Comment by moskoweb** [comment]
Even making this PATH definition, it did not solve it, it continues to inform that the node command not found.

**Comment by cayleyh** [comment]
For anyone who runs across this again, for me the issue was that Nova was not picking up the $PATH correctly from the environment. Nova only looks `.zprofile` or `.zlogin`, but not `.zshrc` (as per https://help.panic.com/nova/environment-variables/). I had everything in `.zshrc` which manifested as this error.
