### ISSUE TITLE
"node:" prefixed imports are incorrect

### ISSUE THREAD

**Issue by robb-j** [apexskier/nova-typescript#450]
When importing using the newer "node:" prefix for code node.js modules, it incorrectly autocompletes and doubles up the prefix.
For example completing from `node:u` gets completed to `node:node:util` rather than `node:util`, I'm not sure if this is an extension thing or a panic thing?

Also it stops offering completions after entering the `:` character.

**To reproduce**

Steps to reproduce the behaviour:

1. Open a TypeScript file
2. Start an import, typing `import {} from "node:u"`
3. Choose the completion for `node:url`
4. See `import {} from "node:node:url"`

**Expected behavior**

It should complete to `import {} from "node:url"`

**Screenshots**

https://user-images.githubusercontent.com/1526174/210185370-5eb65735-a9e0-4649-a952-ed40e66fbb9f.mov

**Environment**

- Nova version: 10.6 (476615)
- Extension version: 2.5.0
- TypeScript version: 4.9.4
- Sidebar information: `Status Running, TypeScript 4.9.4`
- macOS version: 13.1 (22C65)
- NodeJS information:
  - node version: `v18.12.1`
  - npm version: `8.19.2`
  - installation method: https://fnm.vercel.app/

**Extension console output**

Turn on extension development in Nova in Preferences > General > Extension Development. Then open the extension console with Extensions > Show Extension Console and copy anything coming from the Source "TypeScript" or "TypeScript Language Server".
Copying text is preferred over screenshots, for accessibility and searching.

**Additional context**

**Comment by apexskier** [comment]
I've upgraded the underlying language server and bundled typescript version, can you check this again?

**Comment by robb-j** [comment]
It seems to have fixed it, it is no-longer duplicating the "node:" prefix from a quick test. It does still seem to stop offering completions directly after typing the `:` but they appear again afterwards and the completion works. Thank you.
