### ISSUE TITLE
Auto import not working 

### ISSUE THREAD

**Issue by eidellev** [apexskier/nova-typescript#451]
Auto import seems to not be working

**To reproduce**

Use a variable/function from another module, select auto-import from the dropdown menu. 

**Expected behavior**
The selected symbol should be added to the current module's imports

**Screenshots**

![image](https://user-images.githubusercontent.com/11258756/210947974-bb1c8691-a0de-4610-8c0f-17221b2446d0.png)

**Environment**

    Nova version: 10.6
    Extension version: 2.5.0
    macOS version: 13.1
    NodeJS information:
        node version: 18.12.0
        npm version: 8.19.2
        installation method: nvm

**Comment by apexskier** [comment]
I verified this is working today. If you can find more details, let me know.

**Comment by franzwarning** [comment]
Not working for me either.

**Comment by eidellev** [comment]
@franzwarning I tested this with a project without `baseUrl` and it doesn't work either
