### ISSUE TITLE
Autocomplete suggestion layout issues

### ISSUE THREAD

**Issue by soniktrooth** [apexskier/nova-typescript#456]
When this extension is on, the suggestions look like this: 
<img width="513" alt="image" src="https://user-images.githubusercontent.com/597617/213588446-4e7eeeab-45cf-4743-9f95-d17848c9402c.png">

Without it on, obviously the auto import suggestions are no longer there but this same layout issue is not present for the suggestions.

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
