### ISSUE TITLE
Auto Importing Not Working

### ISSUE THREAD

**Issue by franzwarning** [apexskier/nova-typescript#464]
I see this:
<img width="624" alt="ss-2023-02-13 at 21 07 26@2x" src="https://user-images.githubusercontent.com/1596816/218620391-25e3bb79-7360-48a0-be64-1a11742ac71b.png">

I hit enter, and nothing happens. Console looks clear, no obvious errors or logs. Typescript from node_modules, 4.9.4

**Comment by thomasvalera** [comment]
+1

**Comment by grndctrl** [comment]
This has been a problem for a while now for me. Really would like to see this fixed, sometimes it bothers the shit out of me and I angrily load up VSCode. Could it be because I am still on Big Sur?

**Comment by bartembregts** [comment]
Any update?

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
