### ISSUE TITLE
Documentation popups not disablable

### ISSUE THREAD

**Issue by yetzt** [apexskier/nova-typescript#466]
I get unwanted popups with code documentation and it's impossible to disable those specifically without disabling the whole extension. "Disable suggestions" is on, "Include..." is all off. 

**To reproduce**

Write code using `sharp`, have your cursor in the code using `sharp`.

**Expected behavior**

Not seing popups with documentation i don't want to see.

**Screenshots**

![Example](https://i.imgur.com/YQWen6D.png)

**Environment**

- Nova version: 476615
- Extension version: 2.6.0
- macOS version: 12.6.3
- NodeJS information:
  - node version: v18.12.1
  - npm version: 8.19.2
  - installation method: nvm

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
