### ISSUE TITLE
tasks to compile/run

### ISSUE THREAD

**Issue by laralove143** [apexskier/nova-typescript#478]
im not sure if im missing something but i think we have to use a watcher to compile our ts files ourselves, it'd be more convenient if this extension had a setting/command to do that, like webstorm does

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
