### ISSUE TITLE
Server will not start on Nova 11

### ISSUE THREAD

**Issue by ahcurrier** [apexskier/nova-typescript#485]
**To reproduce**

1. Launch Nova 11
2. See error: 'TypeScript Language Server stopped unexpectedly. Task exited with status 127.'

This was working yesterday with Nova 10.

**Expected behavior**

TypeScript Language Server does not stop unexpectedly.

**Environment**

- Nova version: 11 (521513)
- Extension version: 2.6.0
- TypeScript version: 4.2.4
- Sidebar information: not sure what this is
- macOS version: 13.3.1
- NodeJS information:
  - node version: 19.9.0
  - npm version: 9.6.3
  - installation method: nvm

**Extension console output**

TypeScript[12:49:38.170000] activated

TypeScript Language Server[12:49:38.171000] /Users/acurrier/Library/Application Support/Nova/Extensions/apexskier.typescript/run.sh: line 13: node: command not found

TypeScript Language Server[12:49:38.172000] TypeScript Language Server connection closed unexpectedly: Task exited with a non-zero exit status: 127.

**Comment by cora-type** [comment]
having the same issue

**Comment by soniktrooth** [comment]
I get this constantly. Quitting and restarting Nova works sometimes but it seems completely random

**Comment by lachierussell** [comment]
I'm also having this issue. It wasn't a problem until I migrated to a new computer and setup a different shell. Nova won't seem to recognise switching back to the default shell however.

**Comment by lachierussell** [comment]
I don't think this is a great work around, and not sure if there'll be other issues, but I have got it to somewhat work again by adding a symlink to /usr/local/bin for both node and npm. I still get this error: `[tsclient] env: node: No such file or directory` but the rest of the extension seems to work.

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
