### ISSUE TITLE
Inserting text replaces existing code when it probably shouldn't

### ISSUE THREAD

**Issue by orikad** [apexskier/nova-typescript#504]
In many cases when I change a line like:
```typescript
console.log("hello");
```
to:
```typescript
window.console.log("hello");
```
(just a silly example which doesn't make a lot of sense by itself but it occurs in many other cases)
I place the cursor just before `console.` and type `window.` and then the result is
```typescript
window..log("hello");
```
Which is not the intended outcome.
Same thing happens with opening parentheses, e.g. `console.log(1)` -> `console.log(console.log(1))` becomes `console.log(.log("hello"));`.

I'm not sure if the issue lies in the Nova TypeScript implementation or the tsserver it wraps. I'd be happy to contribute a fix if anyone can suggest where it's implemented.

Thanks!

**Environment**

- Nova version: 11.4 Build 540540
- Extension version: v2.6.0
- TypeScript version: Version 5.1.6
- Sidebar information: 4.9.4
- macOS version: 14.0 Beta (23A5312d)
- NodeJS information:
  - node version: v20.5.0
  - npm version:9.8.0
  - installation method: homebrew

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
