### ISSUE TITLE
How to disable the extension in a workspace?

### ISSUE THREAD

**Issue by btd1337** [apexskier/nova-typescript#512]
Hi,

I have a doubt, this extension conflicts with Deno projects.

Deno extensions recommend disabling TypeScript support to work correctly. How to disable the extension only in the workspace running Deno?

Thanks in advance

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
