### ISSUE TITLE
Support Marker Comments

### ISSUE THREAD

**Issue by danhalliday** [apexskier/nova-typescript#518]
What would be involved in supporting marker comments in this extension? I would love to be able to use the section markers popularised by Xcode in my Typescript projects in Nova. In particular, getting a horizontal divider in the editor (similar or identical to Nova’s 'type and function separators'), and being able to browse the markers in the symbol list.

`// MARK: - My Section Title`

I’d be willing to propose a PR for this if anyone can suggest whether it’s actually possible within the extension API and roughly how to approach it.

**Comment by apexskier** [comment]
I personally think this should actually live outside of this extension as a separate extension, since it's not a feature of the typescript language, and would apply to any language.
