### ISSUE TITLE
Automatically add missing imports

### ISSUE THREAD

**Issue by sgwilym** [apexskier/nova-typescript#52]
Trying Nova again since b19 came out, and feeling out the things that are stopping me from jumping ship from VSCode. There's a lot I can live without, but there's one thing that I really feel myself bumping up against.

VSCode automatically creates imports for symbols in two scenarios:

1. Upon autocomplete of certain symbols
2. When a 'add all missing imports' command is run

Method 1 I could live without. It's even a bit overzealous.
Method 2 would be huge. It saves you so much busywork not needing to type out imports and path names yourself.

I'm guessing this feature is something specific to VSCode, rather than TS' language server.

**Comment by sgwilym** [comment]
Sorry, not sure why this was labelled a bug.

**Comment by apexskier** [comment]
This actually _should_ be provided by the Code Action command, but I think I've identified why it doesn't work – when I request code actions I need to tell it about the import error (the language server protocol requires this).

<details>

This
```json
{"seq":1,"type":"request","command":"getCodeFixes","arguments":{"file":"/Volumes/Macintosh HD/Users/cameronlittle/Dev/nova-typescript/src/main.ts", "errorCodes": [2304, 2552], "startLine": 152, "endLine": 152, "startOffset": 27, "endOffset": 28}}
```

produces
```json
{"seq":0,"type":"response","command":"getCodeFixes","request_seq":1,"success":true,"body":[{"fixName":"import","description":"Import 'registerFindReferences' from module \"./commands/findReferences\"","changes":[{"fileName":"/Volumes/Macintosh HD/Users/cameronlittle/Dev/nova-typescript/src/main.ts","textChanges":[{"start":{"line":9,"offset":1},"end":{"line":9,"offset":1},"newText":"import { registerFindReferences } from \"./commands/findReferences\";\n"}]}],"fixId":"fixMissingImport","fixAllDescription":"Add all missing imports"},{"fixName":"import","description":"Import 'registerFindReferences' from module \"./commands/findReferences\"","changes":[{"fileName":"/Volumes/Macintosh HD/Users/cameronlittle/Dev/nova-typescript/src/main.ts","textChanges":[{"start":{"line":9,"offset":1},"end":{"line":9,"offset":1},"newText":"import { registerFindReferences } from \"./commands/findReferences\";\n"}]}],"fixId":"fixMissingImport","fixAllDescription":"Add all missing imports"}]}
```

and this
```json
{"seq":1,"type":"request","command":"getCodeFixes","arguments":{"file":"/Volumes/Macintosh HD/Users/cameronlittle/Dev/nova-typescript/src/main.ts", "errorCodes": [], "startLine": 152, "endLine": 152, "startOffset": 27, "endOffset": 28}}
```

produces
```json
{"seq":1,"type":"request","command":"getCodeFixes","arguments":{"file":"/Volumes/Macintosh HD/Users/cameronlittle/Dev/nova-typescript/src/main.ts", "errorCodes": [], "startLine": 152, "endLine": 152, "startOffset": 27, "endOffset": 28}}
```

</details>

Nova doesn't provide any way for me to get the diagnostic information I need and it intercepts the language server events I'd need to be able to manage them myself. If I hack in the diagnostics manually I can get the auto-import actions to present, but they also show when imports are working. (There's another bug applying them that's unrelated)

I've filed https://dev.panic.com/panic/nova-issues/-/issues/1534, and it sounds like the Nova team is planning on implementing Code Actions directly in Nova, which is the best outcome overall.

**Comment by renodubois** [comment]
Wanted to +1 this feature request and see if things had changed since Nova had officially launched - "Add All Missing Imports" is also one of the core features I use in VS:Code/Vim (via ImportJS) and I'd love to have it in Nova as well!

**Comment by apexskier** [comment]
No changes as of yet. Unfortunately, it looks like the issue tracker isn't public anymore, otherwise [the issue I filed](https://dev.panic.com/panic/nova-issues/-/issues/1534) would be the best place to follow.

**Comment by apexskier** [comment]
This is now supported in Nova 2 with built-in command action support.

**Comment by shahruz** [comment]
@apexskier Is there a specific command to add missing imports? I'm able to do "Organize Imports" but can't find the command for importing missing dependencies.

**Comment by apexskier** [comment]
Editor > Show Code Actions, or <kbd>⌘</kbd><kbd>⇧</kbd><kbd>A</kbd> by default, will show suggested code actions. Your cursor needs to be over an undefined symbol that can be automatically imported.

![Screen Recording 2020-11-22 at 09 18 55](https://user-images.githubusercontent.com/329222/99898714-dc2a8e80-2ca3-11eb-99e4-007b16a30d32.gif)

This is as good as I can make this right now - there's no way to get an auto-import through the LSP without knowing what's broken, and Nova doesn't provide those diagnostics to extensions.

**Comment by shahruz** [comment]
Awesome, I wasn't aware of that Code Actions menu. Thanks so much!

**Comment by joshuajung** [comment]
> VSCode automatically creates imports for symbols in two scenarios:
> 
> 1. Upon autocomplete of certain symbols
> (...)
> 
> Method 1 I could live without. It's even a bit overzealous.

May I ask if implementation of this method 1 (auto import on autocomplete) would be possible in the Nova ecosystem and/or even planned? I'm actually quite a fan of it, as it significantly improves the coding flow when writing a lot of TSX. Thank you!

**Comment by apexskier** [comment]
> > VSCode automatically creates imports for symbols in two scenarios:
> > 
> > 1. Upon autocomplete of certain symbols
> >    (...)
> > 
> > Method 1 I could live without. It's even a bit overzealous.
> 
> May I ask if implementation of this method 1 (auto import on autocomplete) would be possible in the Nova ecosystem and/or even planned? I'm actually quite a fan of it, as it significantly improves the coding flow when writing a lot of TSX. Thank you!

It's currently not feasible due to Nova language server limitations. When using a language server client, autocompletion behavior is completely out of the extension's control (and I don't think it's practical to roll autocompletion by hand).

The language server specification has direct support for additional text edits and commands within a completion item ([see `CompletionItem.additionalTextEdits` and `CompletionItem.command`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/)). If I recall correctly, the underlying [language-server this extension uses adds these additional edits](https://github.com/theia-ide/typescript-language-server/blob/b9cf57816ca07b9b3f3631130b7b5250b0db7ced/server/src/completion.ts#L162-L203), but Nova hasn't implemented support for them.

**Comment by apexskier** [comment]
https://devforum.nova.app/t/language-server-completionitem-additional-edit-command-support/716

**Comment by dlbnco** [comment]
>Editor > Show Code Actions, pressing the lightbulb icon, or ⌘⇧A by default, will show suggested code actions. Your cursor needs to be over an undefined symbol that can be automatically imported.

This works for me but it takes too long for the actions' popover to appear, something like 30 seconds, or even more depending on the symbol. Any thoughts?

**Comment by apexskier** [comment]
@dlbnco It could be Nova, the language server the extension uses, or tsserver itself - those are all involved. The code actions shown by Nova are fetched by Nova directly from the language server, so like [autocompletion](https://github.com/apexskier/nova-typescript/issues/52#issuecomment-809163757), the extension isn't directly invoked.
