### ISSUE TITLE
Extension not running on files with TSX syntax 

### ISSUE THREAD

**Issue by sgwilym** [apexskier/nova-typescript#6]
Hello! Thank you for creating this extension, I've _really_ been looking forward to TS support in Nova. Unfortunately I'm having a problem with it recognising Typescript files with a `.tsx` extension, even though `jsx` is properly configured in my tsconfig.json.

**To Reproduce**
1. Have the typescript extension installed
2. Open a .tsx file with typescript errors in it
3. See no errors
4. Switch syntax from TSX to 'typescript'
5. See errors appear

**Expected behavior**
For the extension to also work on TSX files.

**Environment (please complete the following information):**
- macOS version: 10.15.4
- Nova version: 1.0b10
- Extension version: 1.2.0
- Typescript version: 3.7.2

**Comment by apexskier** [comment]
Thanks for the report! Looks like it's a small oversight, I'll get a fix out shortly.

**Comment by sgwilym** [comment]
Thanks for the quick fix, glad it wasn't too much trouble.
