### ISSUE TITLE
Default key bindings

### ISSUE THREAD

**Issue by apexskier** [apexskier/nova-typescript#7]
Looking for input here. My usual workflow involves vim key-bindings, which don't translate well.

**Comment by apexskier** [comment]
I don't think this are actually extension configurable.

**Comment by apexskier** [comment]
Actually, [the docs](https://novadocs.panic.com/extensions/) say:

> “key-bindings”: **Key Bindings**; extensions which contribute key bindings in Nova’s key binding JSON format

**Comment by olierxleben** [comment]
Hi, I ran into it. I am used to cmd+click (coming from VSCode) and that do something but nothing meaningful, I configured F-keys for your actions, like "jump to definition", in settings of Nova. But I am not sure if one can configure well in extension. I could give it a try if you want.

**Comment by apexskier** [comment]
One additional piece of context:

In beta, I filed a ticket with Panic requesting nova use the Language Server's go to definition functionality when you invoke the built in jump to definition functionality. The fact that this extension provides a separate action is a known issue.

**Comment by olierxleben** [comment]
I am not able to activate the current master in Nova. Nothing happens, no error. I created a dummy project to try out shortcuts (which worked) and wanted to transfer these over to my fork. Nothing happens. I followed your guide at contributing.md - any idea?

**Comment by apexskier** [comment]
Anything in the Extension Console? The only thing I can think of is that `extension.json` is malformed (which shouldn't be the case on master, I just added some basic tests for that) - that's caused silent failures for me before.
