### ISSUE TITLE
Typescript extension crashing Nova

### ISSUE THREAD

**Issue by bdielman** [apexskier/nova-typescript#74]
After installing the Typescript plugin Nova consistently crashes. Sometimes when I click on a file in the file browser after opening the app, other times just a few seconds after opening the app without doing anything. I have had other extensions installed along side Typescript and get the crash. I also get the crash when all other extensions except Typescript are disabled.

**Expected behavior**
Just to be able to use this plugin. 😄 

**Environment (please complete the following information):**

- Nova version: 1.0
- Extension version: 1.6.2
- TypeScript version: 3.9.5
- macOS version: 10.15.6
- NodeJS information:
  - node version: 12.8.0
  - npm version: 6.10.2
  - installation method: Nodenv

**Extension console output**
```
TypeScript[23:35:28.769000] activating...
TypeScript[23:35:29.977000] using tslib at: /Users/dielman/Library/Application Support/Nova/Extensions/apexskier.typescript/node_modules/typescript/lib
TypeScript[23:35:30.016000] activated
```

**Comment by apexskier** [comment]
Since the extension has activated successfully (according to the extensino console) and this is a hard crash, it's most likely a Nova issue, and something I'm not going to be able to figure out without a local reproduction (which I don't have). The most helpful thing would be for you to clone this repo, open the extension locally, and just comment out code to binary search to try to identify what's causing the crash.

I don't expect it's Nodenv causing the issue, since that would most likely cause issues that would crash before "activated" shows up.

**Comment by apexskier** [comment]
Possibly related to https://github.com/apexskier/nova-typescript/issues/64#issuecomment-696921316

**Comment by bdielman** [comment]
This makes sense! Hope they get a fix out soon.

Thanks for looking into this!

**Comment by apexskier** [comment]
I'm now experiencing this after installing node with `asdf` to debug https://github.com/apexskier/nova-typescript/issues/84 and working around the problem in https://github.com/apexskier/nova-typescript/issues/64#issuecomment-696921316, so I now think it's a separate issue.

**Comment by benvp** [comment]
I'm having the same issue using `asdf` for node. @apexskier regarding the comment you linked I do not really understand how to get it working. The automatically generated env variables from the login shell within nova seem correct to me. Do you mind to provide some guidance? :)

**Comment by joshdick** [comment]
Having the same issue with Nova 1.1 and v1.7.0 of this extension. Opening any .ts file with the extension enabled reliably causes an instant crash. I'm uzing zsh as the shell and nodenv for my Node installation, which does correctly appear as part of `$PATH` in Nova's Preferences -> Tools.

**Comment by bdielman** [comment]
> Having the same issue with Nova 1.1 and v1.7.0 of this extension. Opening any .ts file with the extension enabled reliably causes an instant crash. I'm using zsh as the shell and nodenv for my Node installation, which does correctly appear as part of `$PATH` in Nova's Preferences -> Tools.

Same exact setup and issue.

**Comment by apexskier** [comment]
FYI, I'm hiding a few comments here related to https://github.com/apexskier/nova-typescript/issues/64, which I now think is a distinct issue (since I started experiencing crashes myself). fyi @benvp

**Comment by bdielman** [comment]
The latest update for Nova (1.2) seems to have fixed the issue! 🎉
