### ISSUE TITLE
Symlinks

### ISSUE THREAD

**Issue by mindesik** [apexskier/nova-typescript#85]
Hi. I’m working on monorepo and it uses symlinks in workspaces node_modules. The extension does not recognize import/require symlink packages from node_modules.

**Comment by mindesik** [comment]
Screenshot: https://cln.sh/XAuEDp

**Comment by mindesik** [comment]
Screenshot: https://cln.sh/ilYzoq

**Comment by apexskier** [comment]
Thanks for the report! Can you please fill out the full [bug report template](https://github.com/apexskier/nova-typescript/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by apexskier** [comment]
That being said, your screenshot doesn't demonstrate an issue to me. It appears that tsserver is finding `packages/env/index.js` fine, but there's no associated declaration file. It would be helpful if you could provide more information about the filesystem structure of your project, and what you expect to happen.

When I test with a symlink within `node_modules` I have no issues.

<img width="378" alt="Screen Shot 2020-09-23 at 08 29 49" src="https://user-images.githubusercontent.com/329222/93974988-f5cc5a00-fd76-11ea-8dbb-ea59ceac664c.png">
<img width="713" alt="Screen Shot 2020-09-23 at 08 30 20" src="https://user-images.githubusercontent.com/329222/93975027-08469380-fd77-11ea-9f91-e9d85aadfc4c.png">

**Comment by mindesik** [comment]
Sorry, you are right, closing
