### ISSUE TITLE
Autocomplete inserts at beginning of file

### ISSUE THREAD

**Issue by sgwilym** [apexskier/nova-typescript#9]
When suggested autocomplete actions are selected, the suggested edit is added to the beginning of the file instead of wherever the suggestion was made.

Sorry if this is a Nova issue rather than one specific to this extension.

**To Reproduce**
1. Enter part of a autocompleteable statement, such as the name of a package to import.
2. Select the suggestion with the mouse or keyboard.

**Expected behavior**
The suggested change should be entered in the position it was suggested from.

**Screenshots**
![Screen Recording 2020-05-06 at 14 40 39](https://user-images.githubusercontent.com/579491/81196170-fe3a1900-8fbe-11ea-8f41-c12a0a209961.gif)

**Environment (please complete the following information):**
- macOS version: 10.15.3
- Nova version: 1.0b10
- Extension version: 1.3.0
- Typescript version: 3.8.3

**Comment by apexskier** [comment]
I've hit this one as well; I'm pretty confident it's a Nova bug, since this extension doesn't control autocomplete directly.

Cross-filed at https://dev.panic.com/panic/nova-issues/-/issues/943

**Comment by apexskier** [comment]
Still active in beta 12

**Comment by sgwilym** [comment]
Still active in beta 13

**Comment by sgwilym** [comment]
This issue seems to have been fixed, at least in b17?

**Comment by apexskier** [comment]
Seems to be to me, too!
