### ISSUE TITLE
Inline errors and info on hover not working

### ISSUE THREAD

**Issue by bdielman** [apexskier/nova-typescript#90]
I'm on the latest version of both Nova and the Typescript plugin. The crashing I experienced before has been solved, but I'm not seeing any type errors as I work on a file, nor any of the the info on hover. Not sure if it's an issue with my set up or not.

**Expected behavior**
To see type errors and info.

**Environment (please complete the following information):**
- Nova version: 1.2
- Extension version: 1.7.0
- TypeScript version: 4.0.2
- macOS version: 10.15.6
- NodeJS information:
  - node version: 12.16.3
  - npm version: 6.14.4
  - installation method: Nodenv

**Extension console output**
```
TypeScript[19:57:23.215000] activating...
TypeScript[19:57:25.925000] using tslib at: /Users/dielman/Library/Application Support/Nova/Extensions/apexskier.typescript/node_modules/typescript/lib
TypeScript[19:57:25.943000] activated
```

**Comment by apexskier** [comment]
I'm guessing the underlying language server has crashed, similar to https://github.com/apexskier/nova-typescript/issues/91#issuecomment-703063334. Unfortunately, we can't really get any more info without weird hacks.

**Comment by bdielman** [comment]
Just upgraded to the latest version and it looks like everything is working as expected. Thanks @apexskier!
