### ISSUE TITLE
Internal node dependencies not accessible to extension

### ISSUE THREAD

**Issue by kopischke** [apexskier/nova-typescript#96]
The internally installed node dependencies are not accessible to the extension; specifically, the `node_modules` folder ends up inside a `dependencyManagement` folder, resulting in the extension complaining it cannot find the language server.

**To reproduce**

1. Install Nova
2. Install a version 1.0 of this extension (this might not be needed, but that is the update path my config has followed)
3. Let it update to 1.8.1
4. Open the Typescript LSP pane.

**Expected behavior**

The language server is running.

**Actual behavior**

The language server is not running.

**Environment**

- Nova version: 1.2 (207005)
- Extension version: 1.8.1
- TypeScript version: 6.14.8
- Sidebar information: No tslib
- macOS version: 10.14.6
- NodeJS information:
  - node version: v14.12.0
  - npm version: 6.14.8
  - installation method: brew install node

**Extension console output**

TypeScript[20:53:13.781000] typescript lib not found at /Users/martin/Library/Application Support/Nova/Extensions/apexskier.typescript/node_modules/typescript/lib

**Additional context**

Symlinking `dependencyManagement/node_modules` into the extension root solves the issue; reinstalling with the _Force Unlock Dependency Installation_ command does not.

**Comment by apexskier** [comment]
Ah, I made a mistake with https://github.com/apexskier/nova-typescript/commit/80fb5a69357440efa54f88a5928f24b8ffc53337. I didn't test when relying on the internal installation.

**Comment by apexskier** [comment]
Thanks! Fix released in v1.8.2
